# Generated by Django 3.2.6 on 2021-08-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1a',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form1b',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form2a',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form2b',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form3a',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form3b',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form4a',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
        migrations.AddField(
            model_name='form4b',
            name='DayOfWeek',
            field=models.CharField(default='Mon', max_length=200),
        ),
    ]
