# Generated by Django 3.2.6 on 2021-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTB', '0002_auto_20210826_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1a',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form1b',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form2a',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form2b',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form3a',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form3b',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form4a',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='form4b',
            name='DayOfWeek',
            field=models.CharField(max_length=200),
        ),
    ]
